SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off
SecResponseBodyMimeType text/plain text/html text/xml application/json
SecDataDir /tmp/modsecurity
SecAuditEngine RelevantOnly
SecAuditLog /var/log/nginx/modsec_audit.log
SecAuditLogParts ABCFHZ
SecAuditLogType Serial
SecDefaultAction "phase:1,log,auditlog,deny,status:403"
Include /etc/nginx/modsecurity/unicode.mapping
Include /opt/owasp-crs/crs-setup.conf
Include /opt/owasp-crs/rules/*.conf
Include /etc/nginx/modsecurity/ecopoint-rules.conf
